version: '3'

services:
  halo-elite-greetings-discord-bot:
    image: callumhoughton22/halo-elite-greetings-discord-bot
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - GREETINGS_AUDIO_LINK=https://www.youtube.com/watch?v=c_w2Nh-mxH4